# File: .github/workflows/user-action-check.yml

name: User Action Check

on:
  workflow_dispatch: # Allows manual start of the workflow
    inputs:
      repo_url:
        description: "Repository to clone"
        required: true
        default: "https://github.com/KelvinAbidha/Test-course" # Updated URL

jobs:
  action-check:
    runs-on: ubuntu-latest

    steps:
    - name: Clone User-Specified Repository
      run: |
        echo "Cloning repository from: ${{ inputs.repo_url }}"
        git clone ${{ inputs.repo_url }} Test-course
        echo "Repository cloned successfully."

    - name: Debug Directory Listing
      run: |
        echo "Checking contents of Test-course directory..."
        ls -la Test-course

    - name: Wait for User Action
      run: |
        echo "Waiting for 'user-action.txt' to be created in the Test-course directory..."
        for i in {1..10}; do
          if [ -f "Test-course/user-action.txt" ]; then
            echo "User action verified: File 'user-action.txt' exists."
            exit 0
          fi
          echo "File not found. Retrying in 30 seconds..."
          sleep 30
        done
        echo "Validation failed: File 'user-action.txt' not found after waiting."
        exit 1

    - name: Proceed to Next Step
      if: success()
      run: |
        echo "User action validated successfully. Proceeding to the next step."
