# File: .github/workflows/user-action-check.yml

name: User Action Check

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "Repository to clone"
        required: true
        default: "https://github.com/KelvinAbidha/Test-course"

jobs:
  action-check:
    runs-on: ubuntu-latest

    steps:
    - name: Debug Environment Before Clone
      run: |
        echo "Git version:"
        git --version
        echo "Initial directory contents:"
        ls -la

    - name: Clone Repository
      run: |
        echo "Cloning repository from: ${{ inputs.repo_url }}"
        git clone ${{ inputs.repo_url }} Test-course || { echo "Clone failed!"; exit 1; }

    - name: Verify Clone Directory
      run: |
        echo "Checking contents of cloned repository..."
        ls -la Test-course || { echo "Cloned directory not found!"; exit 1; }

    - name: Wait for User Action (Longer Time)
      run: |
        echo "Waiting for 'user-action.txt' to be created in the Test-course directory..."
        for i in {1..20}; do  # Increased retry attempts
          if [ -f "Test-course/user-action.txt" ]; then
            echo "User action verified: File 'user-action.txt' exists."
            exit 0
          fi
          echo "File not found. Retrying in 1 minute..."
          sleep 60  # Increased wait time (1 minute)
        done
        echo "Validation failed: File 'user-action.txt' not found after waiting."
        exit 1

    - name: Proceed to Next Step
      if: success()
      run: |
        echo "User action validated successfully. Proceeding to the next step."
