# File: .github/workflows/user-action-check.yml

name: User Action Check

on:
  workflow_dispatch: # Allows manual start of the workflow
    inputs:
      repo_url:
        description: "Repository to clone"
        required: true
        default: "https://github.com/KelvinAbidha/Test-project.git"

jobs:
  action-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clone User-Specified Repository
      run: |
        echo "Cloning repository from: ${{ inputs.repo_url }}"
        git clone ${{ inputs.repo_url }} Test-project
        echo "Repository cloned successfully."

    - name: Prompt User Action
      run: |
        echo "Action required: Please create a file named 'user-action.txt' in the cloned repository folder."
        echo "Waiting for the user to perform the action..."
        sleep 30  # Simulates waiting time for user action

    - name: Validate User Action
      run: |
        if [ -f "Test-project/user-action.txt" ]; then
          echo "User action verified: File 'user-action.txt' exists."
        else
          echo "Validation failed: File 'user-action.txt' not found."
          exit 1
        fi

    - name: Proceed to Next Step
      if: success()
      run: |
        echo "User action validated successfully. Proceeding to the next step."
