# File: .github/workflows/user-action-check.yml

name: User Action Check

on:
  workflow_dispatch: # Allow manual start of the workfl
    inputs:
      repo_url:
        description: "Repository to clone"
        required: true
        default: "https://github.com/KelvinAbidha/Test-project.git"

jobs:
  action-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clone User-specified Repository
      run: |
        echo "Cloning repository..."
        git clone ${{ inputs.repo_url }}
        echo "Repository cloned successfully."

    - name: User Action Required
      run: |
        echo "Please create a file named 'user-action.txt' in the cloned repository folder."
        echo "This step halts while waiting for the user action..."
        sleep 30 # Simulates waiting time for the user action

    - name: Validate User Action
      run: |
        if [ -f "Test-project/user-action.txt" ]; then
          echo "User action verified! File 'user-action.txt' exists."
        else
          echo "User action not completed. File 'user-action.txt' not found."
          exit 1
        fi

    - name: Proceed to Next Step
      if: success() # Only runs if the previous step succeeds
      run: |
        echo "Proceeding to the next step as the user action is validated."
